apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: mini.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mini
                port:
                  number: 8080

